### PR TITLE
Fix extensions

### PR DESCRIPTION
**Pull request by myhe01**
File extensions with extra dots in their name (e.g. 3.1.1Pic.png) were not letting me compile the doc. Changed these to dashes (e.g.  3-1-1Pic.png).

### CODE REVIEW

**Comment by myhe01** [comment]
Okay, now it's ready

**Review by NChitty — CHANGES_REQUESTED** [review]
Can we give the 3-x-x.png some names that mean something?

**Comment by myhe01** [comment]
> Can we give the 3-x-x.png some names that mean something?

@Caution2TheWind would you be able to rename them please?

**Review by Caution2TheWind — DISMISSED** [review]

**Comment by NChitty** [comment]
@Caution2TheWind or @myhe01 please rename these files when you get the chance

**Pull request merged**
